@echo off
echo 🔧 Creating venv...
python -m venv .venv
call .venv\Scripts\activate
echo 📦 Installing packages...
pip install --upgrade pip
pip install -r requirements.txt
echo 🔐 Decrypting codex.seal...
gpg --quiet --batch --yes --passphrase %SETUP_PASSPHRASE% --output codex.env --decrypt codex.seal
echo 💪 Verifying...
python verify_keys.py
echo 🏗️ Building .exe...
pyinstaller FRED.spec --clean
echo ✅ Done. Run from /dist/FRED_LITIGATION_OS/
